Parameters:
	SnapshotToRestore:
		Type: String
		Default: ""
		Description: Snapshot id to restore DB. leave blank if you are going to start a fresh install
	EnvironmentSize:
		Type: String
		Default: SMALL
		AllowedValues:
			- SMALL
			- MEDIUM
			- LARGE
		Description: Select and environment size (S,M,L) Large environments will deploy an aurora cluster
	DatabaseName:
		Type: String
		Default: MoodleDB
		MinLength: 8
		MaxLength: 64
		AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*" # Start with a letter, alphanumeric characters only
	DatabaseUser:
		Type: String
		Default: moodledude
		MinLength: 8
		MaxLength: 16
		AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*" # Start with a letter, alphanumeric characters only
	DatabasePassword:
		Type: String
		Default: moodledudepassword
		MinLength: 8
		MaxLength: 41
		NoEcho: true
		AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*" # Start with a letter, alphanumeric Characters only
Conditions:
	isLarge:
		!Equals [!Ref EnvironmentSize, "LARGE"]
	isntLarge:
		!Not [!Equals [!Ref EnvironmentSize. "LARGE"]]
	isRestore:
		!Not [!Equals [!Ref SnapshotToRestore, ""]]
Mappings:
	RegionMap:
        us-east-1:
      			"UBUNTU" : "ami-3dec9947" # Ubuntu  2017
    		us-east-2:
      			"UBUNTU" : "ami-597d553c" # Ubuntu  2017
    		us-west-1:
      			"UBUNTU" : "ami-1a17137a" # Ubuntu  2017
    		us-west-2:
      			"UBUNTU" : "ami-a2e544da" # Ubuntu  2017
    		ca-central-1:
      			"UBUNTU" : "ami-b0c67cd4" # Ubuntu  2017
    		eu-west-1:
      			"UBUNTU" : "ami-63b0341a" # Ubuntu  2017
        eu-central-1:
      			"UBUNTU" : "ami-13b8337c" # Ubuntu  2017
    		eu-west-2:
      			"UBUNTU" : "ami-22415846" # Ubuntu  2017
    		ap-southeast-1:
      			"UBUNTU" : "ami-29aece55" # Ubuntu  2017
    		ap-southeast-2:
      			"UBUNTU" : "ami-9b8076f9" # Ubuntu  2017
    		ap-northeast-2:
      			"UBUNTU" : "ami-5027813e" # Ubuntu  2017
    		ap-northeast-1:
      			"UBUNTU" : "ami-42ca4724" # Ubuntu  2017
    		ap-south-1:
      			"UBUNTU" : "ami-84dc94eb" # Ubuntu  2017
    		sa-east-1:
      			"UBUNTU" : "ami-8181c7ed" # Ubuntu  2017

	InstanceSize:
    SMALL:
			"EC2": "t2.micro"
			"DB" : "db.t2.micro"
		MEDIUM:
			"EC2": "t2.small"
			"DB" : "db.t2.small"
		LARGE:
			"EC2": "t2.medium"
			"DB" : "db.r3.xlarge"
Resources:
  ELB:
     Type:
     Properties:
  EC2:
     Type: "AWS::EC2::Instance"
     Properties:
	 ImageId:
	 InstanceType:
  DB:
    Type: "AWS::RDS::DBInstance"
    DeletionPolicy: Snapshot
    Properties:
       AllocatedStorage: 5
       StorageType: gp2
       DBInstanceClass:
       Engine: MySQL
       MasterUserName:
       MasterUserPassword:
  DBAuroraCluster:
	Type: "AWS::RDS::DBCluster"
	DeletionPolicy: Snapshot
	Condition:
	Properties:
		DataBaseName:
		Engine: Aurora
		MasterUserName:
		MasterUserPassword:
		SnapshotIdentifier:
  DBAurora:
	Type:
	Condition:
	Properties:
		DBClusterIdentifier: !Ref DBAuroraCluster
		Engine: Aurora
		DBInstanceClass: !FinInMap [InstanceSize, !Ref Environmentsize, DB]
  S3:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Retain
Outputs:
